
var sc_internal_wrapper = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(sc_internal_wrapper) {
  sc_internal_wrapper = sc_internal_wrapper || {};

var a;a||(a=typeof sc_internal_wrapper !== 'undefined' ? sc_internal_wrapper : {});var g={},k;for(k in a)a.hasOwnProperty(k)&&(g[k]=a[k]);var l=!1,m=!1,n=!1,aa=!1,p=!1;l="object"===typeof window;m="function"===typeof importScripts;n=(aa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!l&&!m;p=!l&&!n&&!m;var q="",r,t,u,v;
if(n)q=__dirname+"/",r=function(b,c){u||(u=require("fs"));v||(v=require("path"));b=v.normalize(b);return u.readFileSync(b,c?null:"utf8")},t=function(b){b=r(b,!0);b.buffer||(b=new Uint8Array(b));b.buffer||w("Assertion failed: undefined");return b},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",w),a.inspect=function(){return"[Emscripten Module object]"};else if(p)"undefined"!=typeof read&&
(r=function(b){return read(b)}),t=function(b){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");"object"===typeof b||w("Assertion failed: undefined");return b},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(l||m)m?q=self.location.href:document.currentScript&&(q=document.currentScript.src),_scriptDir&&(q=_scriptDir),0!==q.indexOf("blob:")?
q=q.substr(0,q.lastIndexOf("/")+1):q="",r=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},m&&(t=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});var x=a.print||console.log.bind(console),y=a.printErr||console.warn.bind(console);for(k in g)g.hasOwnProperty(k)&&(a[k]=g[k]);g=null;var z;a.wasmBinary&&(z=a.wasmBinary);"object"!==typeof WebAssembly&&y("no native wasm support detected");
var A,ba=new WebAssembly.Table({initial:204,maximum:204,element:"anyfunc"}),B=!1,D="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function E(b,c,d){var e=c+d;for(d=c;b[d]&&!(d>=e);)++d;if(16<d-c&&b.subarray&&D)return D.decode(b.subarray(c,d));for(e="";c<d;){var f=b[c++];if(f&128){var h=b[c++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|h);else{var C=b[c++]&63;f=224==(f&240)?(f&15)<<12|h<<6|C:(f&7)<<18|h<<12|C<<6|b[c++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function F(b){return b?E(G,b,void 0):""}
"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var buffer,H,G,I;function N(b){buffer=b;a.HEAP8=H=new Int8Array(b);a.HEAP16=new Int16Array(b);a.HEAP32=I=new Int32Array(b);a.HEAPU8=G=new Uint8Array(b);a.HEAPU16=new Uint16Array(b);a.HEAPU32=new Uint32Array(b);a.HEAPF32=new Float32Array(b);a.HEAPF64=new Float64Array(b)}var O=a.TOTAL_MEMORY||16777216;a.wasmMemory?A=a.wasmMemory:A=new WebAssembly.Memory({initial:O/65536});A&&(buffer=A.buffer);O=buffer.byteLength;N(buffer);I[8576]=5277344;
function P(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c();else{var d=c.O;"number"===typeof d?void 0===c.N?a.dynCall_v(d):a.dynCall_vi(d,c.N):d(void 0===c.N?null:c.N)}}}var Q=[],R=[],ca=[],S=[];function ea(){var b=a.preRun.shift();Q.unshift(b)}var T=0,U=null,V=null;a.preloadedImages={};a.preloadedAudios={};function w(b){if(a.onAbort)a.onAbort(b);x(b);y(b);B=!0;throw new WebAssembly.RuntimeError("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");}
function W(){var b=X;return String.prototype.startsWith?b.startsWith("data:application/octet-stream;base64,"):0===b.indexOf("data:application/octet-stream;base64,")}var X="spirv_cross_wrapper_glsl.wasm";if(!W()){var fa=X;X=a.locateFile?a.locateFile(fa,q):q+fa}function ha(){try{if(z)return new Uint8Array(z);if(t)return t(X);throw"both async and sync fetching of the wasm failed";}catch(b){w(b)}}
function ia(){return z||!l&&!m||"function"!==typeof fetch?new Promise(function(b){b(ha())}):fetch(X,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+X+"'";return b.arrayBuffer()}).catch(function(){return ha()})}R.push({O:function(){ja()}});
var ka=[null,[],[]],la={a:function(b,c,d,e){w("Assertion failed: "+F(b)+", at: "+[c?F(c):"unknown filename",d,e?F(e):"unknown function"])},g:function(){},f:function(){},b:function(){w()},d:function(b,c,d){G.set(G.subarray(c,c+d),b)},e:function(b){var c=H.length;if(2147418112<b)return!1;for(var d=1;4>=d;d*=2){var e=c*(1+.2/d);e=Math.min(e,b+100663296);e=Math.max(16777216,b,e);0<e%65536&&(e+=65536-e%65536);a:{try{A.grow(Math.min(2147418112,e)-buffer.byteLength+65535>>16);N(A.buffer);var f=1;break a}catch(h){}f=
void 0}if(f)return!0}return!1},i:function(){return 0},c:function(){return 0},h:function(b,c,d,e){try{for(var f=0,h=0;h<d;h++){for(var C=I[c+8*h>>2],da=I[c+(8*h+4)>>2],J=0;J<da;J++){var K=G[C+J],L=ka[b];0===K||10===K?((1===b?x:y)(E(L,0)),L.length=0):L.push(K)}f+=da}I[e>>2]=f;return 0}catch(M){return"undefined"!==typeof FS&&M instanceof FS.P||w(M),M.R}},memory:A,table:ba},ma=function(){function b(b){a.asm=b.exports;T--;a.monitorRunDependencies&&a.monitorRunDependencies(T);0==T&&(null!==U&&(clearInterval(U),
U=null),V&&(b=V,V=null,b()))}function c(c){b(c.instance)}function d(b){return ia().then(function(b){return WebAssembly.instantiate(b,e)}).then(b,function(b){y("failed to asynchronously prepare wasm: "+b);w(b)})}var e={env:la,wasi_snapshot_preview1:la};T++;a.monitorRunDependencies&&a.monitorRunDependencies(T);if(a.instantiateWasm)try{return a.instantiateWasm(e,b)}catch(f){return y("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if(z||"function"!==typeof WebAssembly.instantiateStreaming||
W()||"function"!==typeof fetch)return d(c);fetch(X,{credentials:"same-origin"}).then(function(b){return WebAssembly.instantiateStreaming(b,e).then(c,function(b){y("wasm streaming compile failed: "+b);y("falling back to ArrayBuffer instantiation");d(c)})})})();return{}}();a.asm=ma;var ja=a.___wasm_call_ctors=function(){return(ja=a.___wasm_call_ctors=a.asm.j).apply(null,arguments)};
a._sc_internal_get_latest_exception_message=function(){return(a._sc_internal_get_latest_exception_message=a.asm.k).apply(null,arguments)};a._sc_internal_compiler_glsl_new=function(){return(a._sc_internal_compiler_glsl_new=a.asm.l).apply(null,arguments)};a._sc_internal_compiler_glsl_set_options=function(){return(a._sc_internal_compiler_glsl_set_options=a.asm.m).apply(null,arguments)};
a._sc_internal_compiler_glsl_build_combined_image_samplers=function(){return(a._sc_internal_compiler_glsl_build_combined_image_samplers=a.asm.n).apply(null,arguments)};a._sc_internal_compiler_glsl_get_combined_image_samplers=function(){return(a._sc_internal_compiler_glsl_get_combined_image_samplers=a.asm.o).apply(null,arguments)};a._sc_internal_compiler_get_decoration=function(){return(a._sc_internal_compiler_get_decoration=a.asm.p).apply(null,arguments)};
a._sc_internal_compiler_unset_decoration=function(){return(a._sc_internal_compiler_unset_decoration=a.asm.q).apply(null,arguments)};a._sc_internal_compiler_set_decoration=function(){return(a._sc_internal_compiler_set_decoration=a.asm.r).apply(null,arguments)};a._sc_internal_compiler_get_name=function(){return(a._sc_internal_compiler_get_name=a.asm.s).apply(null,arguments)};a._sc_internal_compiler_set_name=function(){return(a._sc_internal_compiler_set_name=a.asm.t).apply(null,arguments)};
a._sc_internal_compiler_get_entry_points=function(){return(a._sc_internal_compiler_get_entry_points=a.asm.u).apply(null,arguments)};a._malloc=function(){return(a._malloc=a.asm.v).apply(null,arguments)};a._free=function(){return(a._free=a.asm.w).apply(null,arguments)};a._sc_internal_compiler_get_cleansed_entry_point_name=function(){return(a._sc_internal_compiler_get_cleansed_entry_point_name=a.asm.x).apply(null,arguments)};
a._sc_internal_compiler_get_shader_resources=function(){return(a._sc_internal_compiler_get_shader_resources=a.asm.y).apply(null,arguments)};a._sc_internal_compiler_get_specialization_constants=function(){return(a._sc_internal_compiler_get_specialization_constants=a.asm.z).apply(null,arguments)};a._sc_internal_compiler_set_scalar_constant=function(){return(a._sc_internal_compiler_set_scalar_constant=a.asm.A).apply(null,arguments)};
a._sc_internal_compiler_get_type=function(){return(a._sc_internal_compiler_get_type=a.asm.B).apply(null,arguments)};a._sc_internal_compiler_get_member_name=function(){return(a._sc_internal_compiler_get_member_name=a.asm.C).apply(null,arguments)};a._sc_internal_compiler_get_member_decoration=function(){return(a._sc_internal_compiler_get_member_decoration=a.asm.D).apply(null,arguments)};
a._sc_internal_compiler_set_member_decoration=function(){return(a._sc_internal_compiler_set_member_decoration=a.asm.E).apply(null,arguments)};a._sc_internal_compiler_get_declared_struct_size=function(){return(a._sc_internal_compiler_get_declared_struct_size=a.asm.F).apply(null,arguments)};a._sc_internal_compiler_get_declared_struct_member_size=function(){return(a._sc_internal_compiler_get_declared_struct_member_size=a.asm.G).apply(null,arguments)};
a._sc_internal_compiler_rename_interface_variable=function(){return(a._sc_internal_compiler_rename_interface_variable=a.asm.H).apply(null,arguments)};a._sc_internal_compiler_get_work_group_size_specialization_constants=function(){return(a._sc_internal_compiler_get_work_group_size_specialization_constants=a.asm.I).apply(null,arguments)};a._sc_internal_compiler_compile=function(){return(a._sc_internal_compiler_compile=a.asm.J).apply(null,arguments)};
a._sc_internal_compiler_delete=function(){return(a._sc_internal_compiler_delete=a.asm.K).apply(null,arguments)};a._sc_internal_free_pointer=function(){return(a._sc_internal_free_pointer=a.asm.L).apply(null,arguments)};a.dynCall_vi=function(){return(a.dynCall_vi=a.asm.M).apply(null,arguments)};a.asm=ma;var Y;a.then=function(b){if(Y)b(a);else{var c=a.onRuntimeInitialized;a.onRuntimeInitialized=function(){c&&c();b(a)}}return a};V=function na(){Y||Z();Y||(V=na)};
function Z(){function b(){if(!Y&&(Y=!0,!B)){P(R);P(ca);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var b=a.postRun.shift();S.unshift(b)}P(S)}}if(!(0<T)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)ea();P(Q);0<T||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}a.run=Z;
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();Z();


  return sc_internal_wrapper
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = sc_internal_wrapper;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return sc_internal_wrapper; });
    else if (typeof exports === 'object')
      exports["sc_internal_wrapper"] = sc_internal_wrapper;
    